# Generated by Django 6.0.7 on 2026-08-25 23:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_income_savingsgoal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='monto')),
                ('date', models.DateField(verbose_name='fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='expenses.savingsgoal', verbose_name='meta de ahorro')),
            ],
            options={
                'verbose_name': 'abono de ahorro',
                'verbose_name_plural': 'abonos de ahorro',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
